### ISSUE TITLE
Allow source and target to be `null`

### ISSUE THREAD

**Issue by joester89** [SAM-IT/abac#1]
https://github.com/SAM-IT/abac/blob/1f6284a5e283631bf8b23a540e85bb1b3d4f66a0/src/connectors/yii2/Manager.php#L23

Volgens mij moet het ook mogelijk zijn om `null` als source en target mee te geven. Null source om te kunnen ondersteunen dat je rechten vraagt over een gebruiker die niet ingelogd is. Null target om op te kunnen vragen of de gebruiker een rol heeft zonder dat daar verder iets aan gekoppeld hoeft te zijn.

**Comment by SamMousa** [comment]
Nee dat is authenticatie; dit gaat alleen over authorization. Je kunt gewoon aan guest authorizable object maken als je dat nodig hebt
